# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-14 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
